screen:
  width: 480
  height: 800
  correction: 80 # the pixels are wrong? wat da fuk

ttl:
  ambient: 120
  background: 300
  calendar: 3600
  clocko: 1
  forecast: 300
  weather: 600

  failure:
    retry: 5
    backoff: 1

logging:
  file: "clocko.log"
  format: "%(asctime)s [%(module)s.%(funcName)s] [%(levelname)s] %(message)s"
  level: 10 #DEBUG: 10, INFO: 20, WARNING: 30, ERROR: 40, CRITICAL: 50
  name: "delphi"

path:
  background: "assets/img/backgrounds"
  font: "assets/font"

api:
  tomorrowio:
    url: "https://api.tomorrow.io/v4/timelines"
  pirateweather:
    url: "https://api.pirateweather.net/forecast/%(apiKey)s/%(lat)s,%(lon)s?exclude=alerts"