DEMODATA = {
    "latitude": 42.473114,
    "longitude": -70.895815,
    "timezone": "Etc/GMT+5",
    "offset": -5.0,
    "elevation": 0,
    "currently":
    {
        "time": 1672682880,
        "summary": "Clear",
        "icon": "clear-day",
        "nearestStormDistance": 0,
        "nearestStormBearing": 0,
        "precipIntensity": 0.0,
        "precipProbability": 0.0,
        "precipIntensityError": 0.0,
        "precipType": "none",
        "temperature": 48.15,
        "apparentTemperature": 43.89,
        "dewPoint": 36.01,
        "humidity": 0.64,
        "pressure": 1016.6,
        "windSpeed": 9.499,
        "windGust": 18.57,
        "windBearing": 294.3,
        "cloudCover": 0.09,
        "uvIndex": 2.2,
        "visibility": 10.0,
        "ozone": 291.14
    },
    "minutely":
    {
        "summary": "Clear",
        "icon": "clear",
        "data":
        [
            {
                "time": 1672682880,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672682940,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683000,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683060,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683120,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683180,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683240,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683300,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683360,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683420,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683480,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683540,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683600,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683660,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683720,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683780,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683840,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683900,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672683960,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684020,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684080,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684140,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684200,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684260,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684320,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684380,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684440,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684500,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684560,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684620,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684680,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684740,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684800,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684860,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684920,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672684980,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685040,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685100,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685160,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685220,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685280,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685340,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685400,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685460,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685520,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685580,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685640,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685700,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685760,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685820,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685880,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672685940,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686000,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686060,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686120,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686180,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686240,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686300,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686360,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686420,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            },
            {
                "time": 1672686480,
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipType": "none"
            }
        ]
    },
    "hourly":
    {
        "summary": "Cloudy",
        "icon": "cloudy",
        "data":
        [
            {
                "time": 1672682400.0,
                "icon": "clear-day",
                "summary": "Clear",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 47.93,
                "apparentTemperature": 43.51,
                "dewPoint": 35.89,
                "humidity": 0.64,
                "pressure": 1016.4,
                "windSpeed": 9.81,
                "windGust": 20.11,
                "windBearing": 294.38,
                "cloudCover": 0.09,
                "uvIndex": 2.2,
                "visibility": 10.0,
                "ozone": 291.14
            },
            {
                "time": 1672686000.0,
                "icon": "partly-cloudy-day",
                "summary": "Partly Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 48.61,
                "apparentTemperature": 44.67,
                "dewPoint": 36.68,
                "humidity": 0.64,
                "pressure": 1016.9,
                "windSpeed": 8.93,
                "windGust": 16.2,
                "windBearing": 296.97,
                "cloudCover": 0.43,
                "uvIndex": 1.88,
                "visibility": 10.0,
                "ozone": 290.43
            },
            {
                "time": 1672689600.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 48.16,
                "apparentTemperature": 44.66,
                "dewPoint": 36.46,
                "humidity": 0.64,
                "pressure": 1016.7,
                "windSpeed": 7.6,
                "windGust": 14.52,
                "windBearing": 290.43,
                "cloudCover": 1.0,
                "uvIndex": 1.14,
                "visibility": 10.0,
                "ozone": 291.38
            },
            {
                "time": 1672693200.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 44.78,
                "apparentTemperature": 42.76,
                "dewPoint": 37.69,
                "humidity": 0.7,
                "pressure": 1016.9,
                "windSpeed": 4.06,
                "windGust": 8.8,
                "windBearing": 273.95,
                "cloudCover": 1.0,
                "uvIndex": 0.41,
                "visibility": 10.0,
                "ozone": 290.28
            },
            {
                "time": 1672696800.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 41.63,
                "apparentTemperature": 38.04,
                "dewPoint": 37.69,
                "humidity": 0.77,
                "pressure": 1018.2,
                "windSpeed": 5.45,
                "windGust": 7.82,
                "windBearing": 270.0,
                "cloudCover": 1.0,
                "uvIndex": 0.02,
                "visibility": 10.0,
                "ozone": 286.85
            },
            {
                "time": 1672700400.0,
                "icon": "partly-cloudy-night",
                "summary": "Partly Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 39.61,
                "apparentTemperature": 35.74,
                "dewPoint": 37.36,
                "humidity": 0.82,
                "pressure": 1018.7,
                "windSpeed": 5.31,
                "windGust": 11.31,
                "windBearing": 273.01,
                "cloudCover": 0.52,
                "uvIndex": 0.0,
                "visibility": 10.0,
                "ozone": 285.58
            },
            {
                "time": 1672704000.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 39.16,
                "apparentTemperature": 34.31,
                "dewPoint": 36.23,
                "humidity": 0.81,
                "pressure": 1018.9,
                "windSpeed": 6.63,
                "windGust": 13.54,
                "windBearing": 278.47,
                "cloudCover": 0.87,
                "uvIndex": 0.0,
                "visibility": 10.0,
                "ozone": 283.98
            },
            {
                "time": 1672707600.0,
                "icon": "clear-night",
                "summary": "Clear",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 38.37,
                "apparentTemperature": 33.72,
                "dewPoint": 35.89,
                "humidity": 0.83,
                "pressure": 1019.3,
                "windSpeed": 6.08,
                "windGust": 12.01,
                "windBearing": 279.25,
                "cloudCover": 0.03,
                "uvIndex": 0.0,
                "visibility": 10.0,
                "ozone": 281.54
            },
            {
                "time": 1672711200.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 37.58,
                "apparentTemperature": 32.52,
                "dewPoint": 35.44,
                "humidity": 0.84,
                "pressure": 1020.3,
                "windSpeed": 6.48,
                "windGust": 12.15,
                "windBearing": 277.43,
                "cloudCover": 0.91,
                "uvIndex": 0.0,
                "visibility": 10.0,
                "ozone": 281.72
            },
            {
                "time": 1672714800.0,
                "icon": "clear-night",
                "summary": "Clear",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 36.91,
                "apparentTemperature": 31.81,
                "dewPoint": 34.77,
                "humidity": 0.84,
                "pressure": 1020.7,
                "windSpeed": 6.33,
                "windGust": 12.57,
                "windBearing": 284.04,
                "cloudCover": 0.14,
                "uvIndex": 0.0,
                "visibility": 9.94,
                "ozone": 279.68
            },
            {
                "time": 1672718400.0,
                "icon": "clear-night",
                "summary": "Clear",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 36.01,
                "apparentTemperature": 31.09,
                "dewPoint": 34.21,
                "humidity": 0.85,
                "pressure": 1020.7,
                "windSpeed": 5.83,
                "windGust": 11.45,
                "windBearing": 291.04,
                "cloudCover": 0.24,
                "uvIndex": 0.0,
                "visibility": 9.69,
                "ozone": 278.68
            },
            {
                "time": 1672722000.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 34.66,
                "apparentTemperature": 29.86,
                "dewPoint": 33.31,
                "humidity": 0.86,
                "pressure": 1020.2,
                "windSpeed": 5.35,
                "windGust": 8.94,
                "windBearing": 285.12,
                "cloudCover": 0.99,
                "uvIndex": 0.0,
                "visibility": 9.32,
                "ozone": 278.98
            },
            {
                "time": 1672725600.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 34.09,
                "apparentTemperature": 29.0,
                "dewPoint": 32.86,
                "humidity": 0.87,
                "pressure": 1020.7,
                "windSpeed": 5.59,
                "windGust": 8.38,
                "windBearing": 272.86,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 9.07,
                "ozone": 276.66
            },
            {
                "time": 1672729200.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 33.42,
                "apparentTemperature": 28.55,
                "dewPoint": 31.96,
                "humidity": 0.85,
                "pressure": 1020.4,
                "windSpeed": 5.18,
                "windGust": 8.24,
                "windBearing": 284.04,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 9.51,
                "ozone": 276.74
            },
            {
                "time": 1672732800.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 33.08,
                "apparentTemperature": 28.3,
                "dewPoint": 31.28,
                "humidity": 0.83,
                "pressure": 1020.4,
                "windSpeed": 5.01,
                "windGust": 7.82,
                "windBearing": 292.99,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 9.82,
                "ozone": 275.55
            },
            {
                "time": 1672736400.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 32.97,
                "apparentTemperature": 28.61,
                "dewPoint": 30.94,
                "humidity": 0.83,
                "pressure": 1020.0,
                "windSpeed": 4.53,
                "windGust": 5.31,
                "windBearing": 326.31,
                "cloudCover": 0.93,
                "uvIndex": 0.0,
                "visibility": 10.0,
                "ozone": 273.47
            },
            {
                "time": 1672740000.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 33.42,
                "apparentTemperature": 29.03,
                "dewPoint": 32.29,
                "humidity": 0.84,
                "pressure": 1019.9,
                "windSpeed": 4.65,
                "windGust": 4.61,
                "windBearing": 237.26,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 8.26,
                "ozone": 273.65
            },
            {
                "time": 1672743600.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 34.09,
                "apparentTemperature": 29.52,
                "dewPoint": 33.31,
                "humidity": 0.86,
                "pressure": 1020.2,
                "windSpeed": 4.97,
                "windGust": 5.31,
                "windBearing": 231.84,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 8.02,
                "ozone": 275.59
            },
            {
                "time": 1672747200.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 35.56,
                "apparentTemperature": 34.61,
                "dewPoint": 34.43,
                "humidity": 0.87,
                "pressure": 1020.5,
                "windSpeed": 2.13,
                "windGust": 3.91,
                "windBearing": 211.61,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 8.7,
                "ozone": 276.94
            },
            {
                "time": 1672750800.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0005,
                "precipProbability": 0.0,
                "precipIntensityError": 0.001,
                "precipAccumulation": 0.0005,
                "precipType": "rain",
                "temperature": 37.58,
                "apparentTemperature": 34.17,
                "dewPoint": 36.57,
                "humidity": 0.87,
                "pressure": 1020.0,
                "windSpeed": 4.34,
                "windGust": 5.45,
                "windBearing": 165.07,
                "cloudCover": 1.0,
                "uvIndex": 0.04,
                "visibility": 8.2,
                "ozone": 277.91
            },
            {
                "time": 1672754400.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.001,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0019,
                "precipAccumulation": 0.001,
                "precipType": "rain",
                "temperature": 39.16,
                "apparentTemperature": 35.67,
                "dewPoint": 38.71,
                "humidity": 0.94,
                "pressure": 1018.8,
                "windSpeed": 4.72,
                "windGust": 9.49,
                "windBearing": 145.84,
                "cloudCover": 1.0,
                "uvIndex": 0.11,
                "visibility": 7.64,
                "ozone": 277.25
            },
            {
                "time": 1672758000.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0014,
                "precipProbability": 0.01,
                "precipIntensityError": 0.0029,
                "precipAccumulation": 0.0014,
                "precipType": "rain",
                "temperature": 40.28,
                "apparentTemperature": 37.01,
                "dewPoint": 39.83,
                "humidity": 0.94,
                "pressure": 1018.9,
                "windSpeed": 4.69,
                "windGust": 6.28,
                "windBearing": 143.47,
                "cloudCover": 1.0,
                "uvIndex": 0.17,
                "visibility": 7.58,
                "ozone": 279.36
            },
            {
                "time": 1672761600.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0078,
                "precipProbability": 0.21,
                "precipIntensityError": 0.0064,
                "precipAccumulation": 0.0078,
                "precipType": "rain",
                "temperature": 40.73,
                "apparentTemperature": 37.35,
                "dewPoint": 40.39,
                "humidity": 0.96,
                "pressure": 1018.0,
                "windSpeed": 4.93,
                "windGust": 7.12,
                "windBearing": 154.89,
                "cloudCover": 1.0,
                "uvIndex": 0.13,
                "visibility": 7.58,
                "ozone": 280.5
            },
            {
                "time": 1672765200.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0141,
                "precipProbability": 0.4,
                "precipIntensityError": 0.0098,
                "precipAccumulation": 0.0141,
                "precipType": "rain",
                "temperature": 40.84,
                "apparentTemperature": 37.8,
                "dewPoint": 40.62,
                "humidity": 0.95,
                "pressure": 1016.6,
                "windSpeed": 4.53,
                "windGust": 5.86,
                "windBearing": 123.69,
                "cloudCover": 1.0,
                "uvIndex": 0.21,
                "visibility": 7.58,
                "ozone": 280.45
            },
            {
                "time": 1672768800.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0204,
                "precipProbability": 0.6,
                "precipIntensityError": 0.0133,
                "precipAccumulation": 0.0204,
                "precipType": "rain",
                "temperature": 41.86,
                "apparentTemperature": 39.2,
                "dewPoint": 41.63,
                "humidity": 0.96,
                "pressure": 1014.9,
                "windSpeed": 4.26,
                "windGust": 7.68,
                "windBearing": 121.61,
                "cloudCover": 1.0,
                "uvIndex": 0.14,
                "visibility": 7.58,
                "ozone": 281.04
            },
            {
                "time": 1672772400.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0352,
                "precipProbability": 0.72,
                "precipIntensityError": 0.0224,
                "precipAccumulation": 0.0352,
                "precipType": "rain",
                "temperature": 42.87,
                "apparentTemperature": 39.33,
                "dewPoint": 42.76,
                "humidity": 0.97,
                "pressure": 1014.2,
                "windSpeed": 5.7,
                "windGust": 9.63,
                "windBearing": 107.1,
                "cloudCover": 1.0,
                "uvIndex": 0.12,
                "visibility": 0.25,
                "ozone": 280.29
            },
            {
                "time": 1672776000.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0501,
                "precipProbability": 0.83,
                "precipIntensityError": 0.0314,
                "precipAccumulation": 0.0501,
                "precipType": "rain",
                "temperature": 43.09,
                "apparentTemperature": 40.21,
                "dewPoint": 42.98,
                "humidity": 0.96,
                "pressure": 1013.2,
                "windSpeed": 4.81,
                "windGust": 8.52,
                "windBearing": 119.54,
                "cloudCover": 1.0,
                "uvIndex": 0.08,
                "visibility": 4.66,
                "ozone": 279.79
            },
            {
                "time": 1672779600.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0649,
                "precipProbability": 0.95,
                "precipIntensityError": 0.0405,
                "precipAccumulation": 0.0649,
                "precipType": "rain",
                "temperature": 43.88,
                "apparentTemperature": 40.24,
                "dewPoint": 43.77,
                "humidity": 0.96,
                "pressure": 1012.2,
                "windSpeed": 6.18,
                "windGust": 8.24,
                "windBearing": 151.7,
                "cloudCover": 1.0,
                "uvIndex": 0.01,
                "visibility": 0.37,
                "ozone": 281.02
            },
            {
                "time": 1672783200.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0665,
                "precipProbability": 0.97,
                "precipIntensityError": 0.0325,
                "precipAccumulation": 0.0665,
                "precipType": "rain",
                "temperature": 43.77,
                "apparentTemperature": 42.99,
                "dewPoint": 43.77,
                "humidity": 0.97,
                "pressure": 1011.7,
                "windSpeed": 2.65,
                "windGust": 4.89,
                "windBearing": 180.0,
                "cloudCover": 1.0,
                "uvIndex": 0.04,
                "visibility": 0.5,
                "ozone": 282.79
            },
            {
                "time": 1672786800.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0682,
                "precipProbability": 0.98,
                "precipIntensityError": 0.0244,
                "precipAccumulation": 0.0682,
                "precipType": "rain",
                "temperature": 43.54,
                "apparentTemperature": 41.78,
                "dewPoint": 43.54,
                "humidity": 0.96,
                "pressure": 1010.6,
                "windSpeed": 3.56,
                "windGust": 4.75,
                "windBearing": 154.44,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 0.19,
                "ozone": 280.25
            },
            {
                "time": 1672790400.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0698,
                "precipProbability": 1.0,
                "precipIntensityError": 0.0164,
                "precipAccumulation": 0.0698,
                "precipType": "rain",
                "temperature": 44.44,
                "apparentTemperature": 41.05,
                "dewPoint": 44.33,
                "humidity": 0.97,
                "pressure": 1010.1,
                "windSpeed": 5.95,
                "windGust": 8.38,
                "windBearing": 170.54,
                "cloudCover": 1.0,
                "uvIndex": 0.02,
                "visibility": 0.19,
                "ozone": 280.1
            },
            {
                "time": 1672794000.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0548,
                "precipProbability": 0.87,
                "precipIntensityError": 0.0182,
                "precipAccumulation": 0.0548,
                "precipType": "rain",
                "temperature": 44.44,
                "apparentTemperature": 42.06,
                "dewPoint": 44.33,
                "humidity": 0.98,
                "pressure": 1009.8,
                "windSpeed": 4.45,
                "windGust": 7.82,
                "windBearing": 212.2,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 0.25,
                "ozone": 281.39
            },
            {
                "time": 1672797600.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0398,
                "precipProbability": 0.74,
                "precipIntensityError": 0.0199,
                "precipAccumulation": 0.0398,
                "precipType": "rain",
                "temperature": 43.66,
                "apparentTemperature": 42.51,
                "dewPoint": 43.54,
                "humidity": 0.98,
                "pressure": 1008.8,
                "windSpeed": 2.96,
                "windGust": 4.75,
                "windBearing": 261.87,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 1.55,
                "ozone": 280.73
            },
            {
                "time": 1672801200.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0248,
                "precipProbability": 0.61,
                "precipIntensityError": 0.0217,
                "precipAccumulation": 0.0248,
                "precipType": "rain",
                "temperature": 42.98,
                "apparentTemperature": 41.24,
                "dewPoint": 42.64,
                "humidity": 0.98,
                "pressure": 1008.4,
                "windSpeed": 3.45,
                "windGust": 6.84,
                "windBearing": 248.63,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 280.3
            },
            {
                "time": 1672804800.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0214,
                "precipProbability": 0.66,
                "precipIntensityError": 0.0188,
                "precipAccumulation": 0.0214,
                "precipType": "rain",
                "temperature": 42.19,
                "apparentTemperature": 40.97,
                "dewPoint": 41.86,
                "humidity": 0.98,
                "pressure": 1007.6,
                "windSpeed": 2.86,
                "windGust": 4.75,
                "windBearing": 313.03,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 278.83
            },
            {
                "time": 1672808400.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0181,
                "precipProbability": 0.72,
                "precipIntensityError": 0.0159,
                "precipAccumulation": 0.0181,
                "precipType": "rain",
                "temperature": 42.08,
                "apparentTemperature": 38.72,
                "dewPoint": 41.29,
                "humidity": 0.96,
                "pressure": 1008.1,
                "windSpeed": 5.23,
                "windGust": 9.91,
                "windBearing": 325.89,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 277.76
            },
            {
                "time": 1672812000.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0147,
                "precipProbability": 0.77,
                "precipIntensityError": 0.013,
                "precipAccumulation": 0.0147,
                "precipType": "rain",
                "temperature": 41.74,
                "apparentTemperature": 38.83,
                "dewPoint": 40.96,
                "humidity": 0.96,
                "pressure": 1007.6,
                "windSpeed": 4.56,
                "windGust": 8.1,
                "windBearing": 332.65,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 276.16
            },
            {
                "time": 1672815600.0,
                "icon": "rain",
                "summary": "Rain",
                "precipIntensity": 0.0113,
                "precipProbability": 0.55,
                "precipIntensityError": 0.011,
                "precipAccumulation": 0.0113,
                "precipType": "rain",
                "temperature": 41.74,
                "apparentTemperature": 39.72,
                "dewPoint": 40.84,
                "humidity": 0.96,
                "pressure": 1008.0,
                "windSpeed": 3.55,
                "windGust": 7.26,
                "windBearing": 315.0,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 278.07
            },
            {
                "time": 1672819200.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.008,
                "precipProbability": 0.32,
                "precipIntensityError": 0.009,
                "precipAccumulation": 0.008,
                "precipType": "rain",
                "temperature": 41.74,
                "apparentTemperature": 41.45,
                "dewPoint": 40.84,
                "humidity": 0.96,
                "pressure": 1008.1,
                "windSpeed": 2.13,
                "windGust": 4.33,
                "windBearing": 336.8,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 277.75
            },
            {
                "time": 1672822800.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0046,
                "precipProbability": 0.1,
                "precipIntensityError": 0.007,
                "precipAccumulation": 0.0046,
                "precipType": "rain",
                "temperature": 41.86,
                "apparentTemperature": 41.13,
                "dewPoint": 40.96,
                "humidity": 0.96,
                "pressure": 1008.8,
                "windSpeed": 2.44,
                "windGust": 3.21,
                "windBearing": 283.24,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 278.03
            },
            {
                "time": 1672826400.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0032,
                "precipProbability": 0.11,
                "precipIntensityError": 0.0047,
                "precipAccumulation": 0.0032,
                "precipType": "rain",
                "temperature": 41.86,
                "apparentTemperature": 42.42,
                "dewPoint": 40.96,
                "humidity": 0.96,
                "pressure": 1009.5,
                "windSpeed": 1.63,
                "windGust": 3.35,
                "windBearing": 329.04,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 277.11
            },
            {
                "time": 1672830000.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0019,
                "precipProbability": 0.11,
                "precipIntensityError": 0.0024,
                "precipAccumulation": 0.0019,
                "precipType": "rain",
                "temperature": 41.86,
                "apparentTemperature": 42.29,
                "dewPoint": 41.07,
                "humidity": 0.96,
                "pressure": 1010.0,
                "windSpeed": 1.7,
                "windGust": 3.07,
                "windBearing": 9.46,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 7.58,
                "ozone": 275.81
            },
            {
                "time": 1672833600.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0006,
                "precipProbability": 0.11,
                "precipIntensityError": 0.0002,
                "precipAccumulation": 0.0006,
                "precipType": "rain",
                "temperature": 41.32,
                "apparentTemperature": 40.65,
                "dewPoint": 40.63,
                "humidity": 0.98,
                "pressure": 1007.21,
                "windSpeed": 2.36,
                "windGust": 2.82,
                "windBearing": 238.25,
                "cloudCover": 1.0,
                "uvIndex": 0.0,
                "visibility": 10.0,
                "ozone": 275.65
            },
            {
                "time": 1672837200.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0004,
                "precipProbability": 0.07,
                "precipIntensityError": 0.0003,
                "precipAccumulation": 0.0004,
                "precipType": "rain",
                "temperature": 42.24,
                "apparentTemperature": 41.12,
                "dewPoint": 41.73,
                "humidity": 0.98,
                "pressure": 1007.34,
                "windSpeed": 2.78,
                "windGust": 4.18,
                "windBearing": 204.72,
                "cloudCover": 1.0,
                "uvIndex": 0.03,
                "visibility": 10.0,
                "ozone": 276.66
            },
            {
                "time": 1672840800.0,
                "icon": "partly-cloudy-day",
                "summary": "Partly Cloudy",
                "precipIntensity": 0.0002,
                "precipProbability": 0.04,
                "precipIntensityError": 0.0005,
                "precipAccumulation": 0.0002,
                "precipType": "rain",
                "temperature": 44.39,
                "apparentTemperature": 42.98,
                "dewPoint": 43.77,
                "humidity": 0.98,
                "pressure": 1007.68,
                "windSpeed": 3.32,
                "windGust": 7.93,
                "windBearing": 214.37,
                "cloudCover": 0.62,
                "uvIndex": 0.46,
                "visibility": 10.0,
                "ozone": 275.9
            },
            {
                "time": 1672844400.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 47.49,
                "apparentTemperature": 46.22,
                "dewPoint": 46.06,
                "humidity": 0.95,
                "pressure": 1007.81,
                "windSpeed": 3.66,
                "windGust": 6.97,
                "windBearing": 205.27,
                "cloudCover": 1.0,
                "uvIndex": 1.32,
                "visibility": 10.0,
                "ozone": 276.24
            },
            {
                "time": 1672848000.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 50.16,
                "apparentTemperature": 51.57,
                "dewPoint": 47.99,
                "humidity": 0.92,
                "pressure": 1007.76,
                "windSpeed": 3.19,
                "windGust": 6.69,
                "windBearing": 228.07,
                "cloudCover": 1.0,
                "uvIndex": 1.9,
                "visibility": 10.0,
                "ozone": 275.33
            },
            {
                "time": 1672851600.0,
                "icon": "cloudy",
                "summary": "Cloudy",
                "precipIntensity": 0.0,
                "precipProbability": 0.0,
                "precipIntensityError": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperature": 52.19,
                "apparentTemperature": 54.22,
                "dewPoint": 49.41,
                "humidity": 0.9,
                "pressure": 1007.28,
                "windSpeed": 2.48,
                "windGust": 5.05,
                "windBearing": 230.83,
                "cloudCover": 1.0,
                "uvIndex": 2.24,
                "visibility": 10.0,
                "ozone": 274.22
            }
        ]
    },
    "daily":
    {
        "summary": "Rain",
        "icon": "rain",
        "data":
        [
            {
                "time": 1672635600,
                "icon": "partly-cloudy-day",
                "summary": "Partly Cloudy",
                "sunriseTime": 1672661612,
                "sunsetTime": 1672694507,
                "moonPhase": 0.36521376682148393,
                "precipIntensity": 0.0,
                "precipIntensityMax": 0.0,
                "precipIntensityMaxTime": 1672682400,
                "precipProbability": 0.0,
                "precipAccumulation": 0.0,
                "precipType": "none",
                "temperatureHigh": 48.61,
                "temperatureHighTime": 1672686000,
                "temperatureLow": 33.42,
                "temperatureLowTime": 1672729200,
                "apparentTemperatureHigh": 44.67,
                "apparentTemperatureHighTime": 1672686000,
                "apparentTemperatureLow": 28.55,
                "apparentTemperatureLowTime": 1672729200,
                "dewPoint": 35.46,
                "humidity": 0.782,
                "pressure": 1018.93,
                "windSpeed": 6.33,
                "windGust": 11.86,
                "windBearing": 282.21,
                "cloudCover": 0.659,
                "uvIndex": 2.2,
                "uvIndexTime": 1672682400,
                "visibility": 10.0,
                "temperatureMin": 33.42,
                "temperatureMinTime": 1672729200,
                "temperatureMax": 48.61,
                "temperatureMaxTime": 1672686000,
                "apparentTemperatureMin": 28.55,
                "apparentTemperatureMinTime": 1672729200,
                "apparentTemperatureMax": 44.67,
                "apparentTemperatureMaxTime": 1672686000
            },
            {
                "time": 1672722000,
                "icon": "rain",
                "summary": "Rain",
                "sunriseTime": 1672748014,
                "sunsetTime": 1672780962,
                "moonPhase": 0.39578023897423686,
                "precipIntensity": 0.0254,
                "precipIntensityMax": 0.0698,
                "precipIntensityMaxTime": 1672736400,
                "precipProbability": 1.0,
                "precipAccumulation": 0.5847,
                "precipType": "rain",
                "temperatureHigh": 44.44,
                "temperatureHighTime": 1672736400,
                "temperatureLow": 32.97,
                "temperatureLowTime": 1672682400,
                "apparentTemperatureHigh": 42.99,
                "apparentTemperatureHighTime": 1672729200,
                "apparentTemperatureLow": 28.61,
                "apparentTemperatureLowTime": 1672682400,
                "dewPoint": 40.23,
                "humidity": 0.94,
                "pressure": 1013.83,
                "windSpeed": 4.33,
                "windGust": 6.73,
                "windBearing": 206.7,
                "cloudCover": 0.997,
                "uvIndex": 0.21,
                "uvIndexTime": 1672711200,
                "visibility": 5.53,
                "temperatureMin": 32.97,
                "temperatureMinTime": 1672682400,
                "temperatureMax": 44.44,
                "temperatureMaxTime": 1672736400,
                "apparentTemperatureMin": 28.61,
                "apparentTemperatureMinTime": 1672682400,
                "apparentTemperatureMax": 42.99,
                "apparentTemperatureMaxTime": 1672729200
            },
            {
                "time": 1672808400,
                "icon": "rain",
                "summary": "Rain",
                "sunriseTime": 1672834413,
                "sunsetTime": 1672867417,
                "moonPhase": 0.4291254813226947,
                "precipIntensity": 0.0042,
                "precipIntensityMax": 0.0127,
                "precipIntensityMaxTime": 1672761600,
                "precipProbability": 0.499,
                "precipAccumulation": 0.0967,
                "precipType": "rain",
                "temperatureHigh": 53.97,
                "temperatureHighTime": 1672718400,
                "temperatureLow": 41.32,
                "temperatureLowTime": 1672693200,
                "apparentTemperatureHigh": 56.65,
                "apparentTemperatureHighTime": 1672718400,
                "apparentTemperatureLow": 38.91,
                "apparentTemperatureLowTime": 1672693200,
                "dewPoint": 45.17,
                "humidity": 0.958,
                "pressure": 1007.96,
                "windSpeed": 5.09,
                "windGust": 10.19,
                "windBearing": 130.09,
                "cloudCover": 0.989,
                "uvIndex": 2.24,
                "uvIndexTime": 1672711200,
                "visibility": 8.31,
                "temperatureMin": 41.32,
                "temperatureMinTime": 1672693200,
                "temperatureMax": 53.97,
                "temperatureMaxTime": 1672718400,
                "apparentTemperatureMin": 38.91,
                "apparentTemperatureMinTime": 1672693200,
                "apparentTemperatureMax": 56.65,
                "apparentTemperatureMaxTime": 1672718400
            },
            {
                "time": 1672894800,
                "icon": "rain",
                "summary": "Rain",
                "sunriseTime": 1672920810,
                "sunsetTime": 1672953875,
                "moonPhase": 0.45969195347544767,
                "precipIntensity": 0.0103,
                "precipIntensityMax": 0.0178,
                "precipIntensityMaxTime": 1672693200,
                "precipProbability": 0.682,
                "precipAccumulation": 0.2366,
                "precipType": "rain",
                "temperatureHigh": 43.55,
                "temperatureHighTime": 1672682400,
                "temperatureLow": 35.32,
                "temperatureLowTime": 1672743600,
                "apparentTemperatureHigh": 37.35,
                "apparentTemperatureHighTime": 1672682400,
                "apparentTemperatureLow": 26.55,
                "apparentTemperatureLowTime": 1672743600,
                "dewPoint": 34.99,
                "humidity": 0.893,
                "pressure": 1014.76,
                "windSpeed": 14.04,
                "windGust": 25.68,
                "windBearing": 41.71,
                "cloudCover": 1.0,
                "uvIndex": 0.38,
                "uvIndexTime": 1672714800,
                "visibility": 10.0,
                "temperatureMin": 35.32,
                "temperatureMinTime": 1672743600,
                "temperatureMax": 43.55,
                "temperatureMaxTime": 1672682400,
                "apparentTemperatureMin": 26.55,
                "apparentTemperatureMinTime": 1672743600,
                "apparentTemperatureMax": 37.35,
                "apparentTemperatureMaxTime": 1672682400
            },
            {
                "time": 1672981200,
                "icon": "rain",
                "summary": "Rain",
                "sunriseTime": 1673007205,
                "sunsetTime": 1673040334,
                "moonPhase": 0.49025842562820066,
                "precipIntensity": 0.0086,
                "precipIntensityMax": 0.0148,
                "precipIntensityMaxTime": 1672714800,
                "precipProbability": 0.504,
                "precipAccumulation": 0.1973,
                "precipType": "rain",
                "temperatureHigh": 37.17,
                "temperatureHighTime": 1672700400,
                "temperatureLow": 29.15,
                "temperatureLowTime": 1672761600,
                "apparentTemperatureHigh": 29.06,
                "apparentTemperatureHighTime": 1672696800,
                "apparentTemperatureLow": 20.89,
                "apparentTemperatureLowTime": 1672761600,
                "dewPoint": 32.23,
                "humidity": 0.932,
                "pressure": 1011.63,
                "windSpeed": 11.89,
                "windGust": 23.11,
                "windBearing": 99.47,
                "cloudCover": 0.954,
                "uvIndex": 0.33,
                "uvIndexTime": 1672711200,
                "visibility": 4.86,
                "temperatureMin": 29.15,
                "temperatureMinTime": 1672761600,
                "temperatureMax": 37.17,
                "temperatureMaxTime": 1672700400,
                "apparentTemperatureMin": 20.89,
                "apparentTemperatureMinTime": 1672761600,
                "apparentTemperatureMax": 29.06,
                "apparentTemperatureMaxTime": 1672696800
            },
            {
                "time": 1673067600,
                "icon": "partly-cloudy-day",
                "summary": "Partly Cloudy",
                "sunriseTime": 1673093597,
                "sunsetTime": 1673126795,
                "moonPhase": 0.5208248977809535,
                "precipIntensity": 0.0,
                "precipIntensityMax": 0.0,
                "precipIntensityMaxTime": 1672682400,
                "precipProbability": 0.082,
                "precipAccumulation": 0.0,
                "precipType": "rain",
                "temperatureHigh": 39.48,
                "temperatureHighTime": 1672714800,
                "temperatureLow": 27.14,
                "temperatureLowTime": 1672693200,
                "apparentTemperatureHigh": 33.51,
                "apparentTemperatureHighTime": 1672714800,
                "apparentTemperatureLow": 23.64,
                "apparentTemperatureLowTime": 1672693200,
                "dewPoint": 30.27,
                "humidity": 0.873,
                "pressure": 1010.0,
                "windSpeed": 6.75,
                "windGust": 15.56,
                "windBearing": 279.07,
                "cloudCover": 0.498,
                "uvIndex": 1.53,
                "uvIndexTime": 1672714800,
                "visibility": 10.0,
                "temperatureMin": 27.14,
                "temperatureMinTime": 1672693200,
                "temperatureMax": 39.48,
                "temperatureMaxTime": 1672714800,
                "apparentTemperatureMin": 23.64,
                "apparentTemperatureMinTime": 1672693200,
                "apparentTemperatureMax": 33.51,
                "apparentTemperatureMaxTime": 1672714800
            },
            {
                "time": 1673154000,
                "icon": "partly-cloudy-day",
                "summary": "Partly Cloudy",
                "sunriseTime": 1673179987,
                "sunsetTime": 1673213257,
                "moonPhase": 0.5486125997380017,
                "precipIntensity": 0.0,
                "precipIntensityMax": 0.0,
                "precipIntensityMaxTime": 1672682400,
                "precipProbability": 0.097,
                "precipAccumulation": 0.0,
                "precipType": "rain",
                "temperatureHigh": 38.05,
                "temperatureHighTime": 1672714800,
                "temperatureLow": 29.36,
                "temperatureLowTime": 1672761600,
                "apparentTemperatureHigh": 32.67,
                "apparentTemperatureHighTime": 1672714800,
                "apparentTemperatureLow": 22.46,
                "apparentTemperatureLowTime": 1672761600,
                "dewPoint": 26.11,
                "humidity": 0.773,
                "pressure": 1017.18,
                "windSpeed": 7.02,
                "windGust": 14.4,
                "windBearing": 235.29,
                "cloudCover": 0.485,
                "uvIndex": 1.55,
                "uvIndexTime": 1672714800,
                "visibility": 10.0,
                "temperatureMin": 29.36,
                "temperatureMinTime": 1672761600,
                "temperatureMax": 38.05,
                "temperatureMaxTime": 1672714800,
                "apparentTemperatureMin": 22.46,
                "apparentTemperatureMinTime": 1672761600,
                "apparentTemperatureMax": 32.67,
                "apparentTemperatureMaxTime": 1672714800
            },
            {
                "time": 1673240400,
                "icon": "cloudy",
                "summary": "Cloudy",
                "sunriseTime": 1673266374,
                "sunsetTime": 1673299720,
                "moonPhase": 0.5791790718907547,
                "precipIntensity": 0.0,
                "precipIntensityMax": 0.0,
                "precipIntensityMaxTime": 1672682400,
                "precipProbability": 0.134,
                "precipAccumulation": 0.0,
                "precipType": "rain",
                "temperatureHigh": 34.51,
                "temperatureHighTime": 1672714800,
                "temperatureLow": 28.04,
                "temperatureLowTime": 1672693200,
                "apparentTemperatureHigh": 30.57,
                "apparentTemperatureHighTime": 1672714800,
                "apparentTemperatureLow": 21.37,
                "apparentTemperatureLowTime": 1672693200,
                "dewPoint": 25.6,
                "humidity": 0.767,
                "pressure": 1022.96,
                "windSpeed": 4.98,
                "windGust": 9.0,
                "windBearing": 111.88,
                "cloudCover": 0.875,
                "uvIndex": 1.28,
                "uvIndexTime": 1672714800,
                "visibility": 10.0,
                "temperatureMin": 28.04,
                "temperatureMinTime": 1672693200,
                "temperatureMax": 34.51,
                "temperatureMaxTime": 1672714800,
                "apparentTemperatureMin": 21.37,
                "apparentTemperatureMinTime": 1672693200,
                "apparentTemperatureMax": 30.57,
                "apparentTemperatureMaxTime": 1672714800
            }
        ]
    },
    "flags":
    {
        "sources":
        [
            "ETOPO1",
            "gfs",
            "gefs",
            "hrrrsubh",
            "hrrr"
        ],
        "sourceTimes":
        {
            "hrrr_0-18": "2023-01-02 16:00:00",
            "hrrr_subh": "2023-01-02 16:00:00",
            "hrrr_18-48": "2023-01-02 12:00:00",
            "gfs": "2023-01-02 12:00:00",
            "gefs": "2023-01-02 06:00:00"
        },
        "nearest-station": 0,
        "units": "us",
        "version": "V1.1.10"
    }
}